services:
  panel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BFF_ORIGIN=https://api.bcalixte.cc.cd
